
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act5_analisis_sintactico;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser5 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser5() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser5(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser5(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\103\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\002\003" +
    "\000\002\003\005\000\002\004\003\000\002\004\004\000" +
    "\002\005\005\000\002\006\003\000\002\006\005\000\002" +
    "\007\006\000\002\007\007\000\002\010\004\000\002\010" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\004\000\002\012\006\000\002\013\010\000" +
    "\002\013\006\000\002\030\004\000\002\030\002\000\002" +
    "\014\011\000\002\015\004\000\002\015\002\000\002\016" +
    "\003\000\002\016\003\000\002\016\003\000\002\016\005" +
    "\000\002\016\004\000\002\017\007\000\002\020\007\000" +
    "\002\021\006\000\002\021\006\000\002\022\003\000\002" +
    "\022\005\000\002\023\003\000\002\023\005\000\002\024" +
    "\003\000\002\031\005\000\002\031\005\000\002\031\005" +
    "\000\002\031\005\000\002\031\005\000\002\031\005\000" +
    "\002\031\005\000\002\031\004\000\002\031\005\000\002" +
    "\031\003\000\002\031\003\000\002\025\003\000\002\025" +
    "\003\000\002\025\003\000\002\025\003\000\002\025\003" +
    "\000\002\025\003\000\002\025\003\000\002\026\003\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\012\004\013\005\004\006\012\010\011\001" +
    "\002\000\004\043\020\001\002\000\004\002\ufffd\001\002" +
    "\000\004\006\012\001\002\000\006\005\004\006\012\001" +
    "\002\000\006\005\004\006\ufffa\001\002\000\004\043\076" +
    "\001\002\000\004\043\024\001\002\000\004\043\020\001" +
    "\002\000\004\002\016\001\002\000\004\002\ufffc\001\002" +
    "\000\004\002\001\001\002\000\006\023\022\024\021\001" +
    "\002\000\006\023\ufff7\024\ufff7\001\002\000\004\043\023" +
    "\001\002\000\006\005\ufffb\006\ufffb\001\002\000\006\023" +
    "\ufff6\024\ufff6\001\002\000\004\025\025\001\002\000\030" +
    "\003\042\007\041\010\011\013\030\014\040\015\046\016" +
    "\032\017\035\020\036\026\044\043\043\001\002\000\030" +
    "\003\uffef\007\uffef\010\uffef\013\uffef\014\uffef\015\uffef\016" +
    "\uffef\017\uffef\020\uffef\026\uffef\043\uffef\001\002\000\004" +
    "\043\043\001\002\000\004\043\uffcc\001\002\000\030\003" +
    "\ufff1\007\ufff1\010\ufff1\013\ufff1\014\ufff1\015\ufff1\016\ufff1" +
    "\017\ufff1\020\ufff1\026\ufff1\043\ufff1\001\002\000\004\043" +
    "\uffc9\001\002\000\004\026\065\001\002\000\030\003\ufff0" +
    "\007\ufff0\010\ufff0\013\ufff0\014\ufff0\015\ufff0\016\ufff0\017" +
    "\ufff0\020\ufff0\026\ufff0\043\ufff0\001\002\000\004\043\uffc8" +
    "\001\002\000\004\043\uffc7\001\002\000\030\003\042\007" +
    "\041\010\011\013\030\014\040\015\046\016\032\017\035" +
    "\020\036\026\ufff2\043\043\001\002\000\004\043\uffcb\001" +
    "\002\000\020\013\030\014\040\015\046\016\032\017\035" +
    "\020\036\043\043\001\002\000\004\023\047\001\002\000" +
    "\032\023\uffc5\030\uffc5\031\uffc5\032\uffc5\033\uffc5\034\uffc5" +
    "\035\uffc5\036\uffc5\037\uffc5\040\uffc5\041\uffc5\043\uffc5\001" +
    "\002\000\004\002\ufff5\001\002\000\004\043\uffc6\001\002" +
    "\000\004\043\uffca\001\002\000\030\003\uffee\007\uffee\010" +
    "\uffee\013\uffee\014\uffee\015\uffee\016\uffee\017\uffee\020\uffee" +
    "\026\uffee\043\uffee\001\002\000\004\043\043\001\002\000" +
    "\006\023\052\032\053\001\002\000\030\003\uffeb\007\uffeb" +
    "\010\uffeb\013\uffeb\014\uffeb\015\uffeb\016\uffeb\017\uffeb\020" +
    "\uffeb\026\uffeb\043\uffeb\001\002\000\016\021\060\022\056" +
    "\044\054\045\061\046\062\047\057\001\002\000\026\023" +
    "\uffc4\030\uffc4\031\uffc4\033\uffc4\034\uffc4\035\uffc4\036\uffc4" +
    "\037\uffc4\040\uffc4\041\uffc4\001\002\000\004\023\063\001" +
    "\002\000\026\023\uffbf\030\uffbf\031\uffbf\033\uffbf\034\uffbf" +
    "\035\uffbf\036\uffbf\037\uffbf\040\uffbf\041\uffbf\001\002\000" +
    "\026\023\uffc1\030\uffc1\031\uffc1\033\uffc1\034\uffc1\035\uffc1" +
    "\036\uffc1\037\uffc1\040\uffc1\041\uffc1\001\002\000\026\023" +
    "\uffc0\030\uffc0\031\uffc0\033\uffc0\034\uffc0\035\uffc0\036\uffc0" +
    "\037\uffc0\040\uffc0\041\uffc0\001\002\000\026\023\uffc3\030" +
    "\uffc3\031\uffc3\033\uffc3\034\uffc3\035\uffc3\036\uffc3\037\uffc3" +
    "\040\uffc3\041\uffc3\001\002\000\026\023\uffc2\030\uffc2\031" +
    "\uffc2\033\uffc2\034\uffc2\035\uffc2\036\uffc2\037\uffc2\040\uffc2" +
    "\041\uffc2\001\002\000\030\003\uffec\007\uffec\010\uffec\013" +
    "\uffec\014\uffec\015\uffec\016\uffec\017\uffec\020\uffec\026\uffec" +
    "\043\uffec\001\002\000\004\026\ufff3\001\002\000\004\002" +
    "\ufff4\001\002\000\010\023\uffe9\031\070\032\071\001\002" +
    "\000\012\023\uffdc\030\uffdc\031\uffdc\032\uffdc\001\002\000" +
    "\004\043\043\001\002\000\016\021\060\022\056\044\054" +
    "\045\061\046\062\047\057\001\002\000\004\023\073\001" +
    "\002\000\030\003\uffed\007\uffed\010\uffed\013\uffed\014\uffed" +
    "\015\uffed\016\uffed\017\uffed\020\uffed\026\uffed\043\uffed\001" +
    "\002\000\004\023\uffea\001\002\000\012\023\uffdb\030\uffdb" +
    "\031\uffdb\032\uffdb\001\002\000\004\027\077\001\002\000" +
    "\004\030\100\001\002\000\004\025\101\001\002\000\016" +
    "\003\107\011\106\012\104\026\uffe6\032\110\043\043\001" +
    "\002\000\016\003\107\011\106\012\104\026\uffe6\032\110" +
    "\043\043\001\002\000\016\003\uffe5\011\uffe5\012\uffe5\026" +
    "\uffe5\032\uffe5\043\uffe5\001\002\000\004\027\156\001\002" +
    "\000\016\003\uffe3\011\uffe3\012\uffe3\026\uffe3\032\uffe3\043" +
    "\uffe3\001\002\000\004\027\152\001\002\000\004\023\151" +
    "\001\002\000\024\021\060\022\056\027\115\042\117\043" +
    "\043\044\054\045\061\046\062\047\057\001\002\000\016" +
    "\003\uffe4\011\uffe4\012\uffe4\026\uffe4\032\uffe4\043\uffe4\001" +
    "\002\000\004\026\146\001\002\000\004\032\114\001\002" +
    "\000\026\003\121\021\060\022\056\027\115\042\117\043" +
    "\043\044\054\045\061\046\062\047\057\001\002\000\024" +
    "\021\060\022\056\027\115\042\117\043\043\044\054\045" +
    "\061\046\062\047\057\001\002\000\026\023\uffcd\030\uffcd" +
    "\031\uffcd\033\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\040" +
    "\uffcd\041\uffcd\001\002\000\024\021\060\022\056\027\115" +
    "\042\117\043\043\044\054\045\061\046\062\047\057\001" +
    "\002\000\022\023\126\033\125\034\127\035\132\036\130" +
    "\037\124\040\133\041\131\001\002\000\004\023\123\001" +
    "\002\000\026\023\uffce\030\uffce\031\uffce\033\uffce\034\uffce" +
    "\035\uffce\036\uffce\037\uffce\040\uffce\041\uffce\001\002\000" +
    "\016\003\uffdd\011\uffdd\012\uffdd\026\uffdd\032\uffdd\043\uffdd" +
    "\001\002\000\024\021\060\022\056\027\115\042\117\043" +
    "\043\044\054\045\061\046\062\047\057\001\002\000\024" +
    "\021\060\022\056\027\115\042\117\043\043\044\054\045" +
    "\061\046\062\047\057\001\002\000\016\003\uffde\011\uffde" +
    "\012\uffde\026\uffde\032\uffde\043\uffde\001\002\000\024\021" +
    "\060\022\056\027\115\042\117\043\043\044\054\045\061" +
    "\046\062\047\057\001\002\000\024\021\060\022\056\027" +
    "\115\042\117\043\043\044\054\045\061\046\062\047\057" +
    "\001\002\000\024\021\060\022\056\027\115\042\117\043" +
    "\043\044\054\045\061\046\062\047\057\001\002\000\024" +
    "\021\060\022\056\027\115\042\117\043\043\044\054\045" +
    "\061\046\062\047\057\001\002\000\024\021\060\022\056" +
    "\027\115\042\117\043\043\044\054\045\061\046\062\047" +
    "\057\001\002\000\026\023\uffd6\030\uffd6\031\uffd6\033\125" +
    "\034\127\035\132\036\130\037\124\040\uffd6\041\uffd6\001" +
    "\002\000\026\023\uffd3\030\uffd3\031\uffd3\033\uffd3\034\uffd3" +
    "\035\uffd3\036\uffd3\037\uffd3\040\uffd3\041\uffd3\001\002\000" +
    "\026\023\uffd7\030\uffd7\031\uffd7\033\125\034\127\035\132" +
    "\036\130\037\124\040\133\041\uffd7\001\002\000\026\023" +
    "\uffd2\030\uffd2\031\uffd2\033\uffd2\034\uffd2\035\uffd2\036\uffd2" +
    "\037\uffd2\040\uffd2\041\uffd2\001\002\000\026\023\uffd4\030" +
    "\uffd4\031\uffd4\033\uffd4\034\uffd4\035\132\036\130\037\124" +
    "\040\uffd4\041\uffd4\001\002\000\026\023\uffd5\030\uffd5\031" +
    "\uffd5\033\uffd5\034\uffd5\035\132\036\130\037\124\040\uffd5" +
    "\041\uffd5\001\002\000\026\023\uffd1\030\uffd1\031\uffd1\033" +
    "\uffd1\034\uffd1\035\uffd1\036\uffd1\037\uffd1\040\uffd1\041\uffd1" +
    "\001\002\000\026\023\uffd0\030\uffd0\031\uffd0\033\uffd0\034" +
    "\uffd0\035\uffd0\036\uffd0\037\uffd0\040\uffd0\041\uffd0\001\002" +
    "\000\022\030\145\033\125\034\127\035\132\036\130\037" +
    "\124\040\133\041\131\001\002\000\026\023\uffcf\030\uffcf" +
    "\031\uffcf\033\uffcf\034\uffcf\035\uffcf\036\uffcf\037\uffcf\040" +
    "\uffcf\041\uffcf\001\002\000\032\002\uffe8\003\uffe8\007\uffe8" +
    "\010\uffe8\013\uffe8\014\uffe8\015\uffe8\016\uffe8\017\uffe8\020" +
    "\uffe8\026\uffe8\043\uffe8\001\002\000\022\023\150\033\125" +
    "\034\127\035\132\036\130\037\124\040\133\041\131\001" +
    "\002\000\016\003\uffe2\011\uffe2\012\uffe2\026\uffe2\032\uffe2" +
    "\043\uffe2\001\002\000\016\003\uffe1\011\uffe1\012\uffe1\026" +
    "\uffe1\032\uffe1\043\uffe1\001\002\000\004\043\043\001\002" +
    "\000\006\030\154\031\070\001\002\000\004\023\155\001" +
    "\002\000\016\003\uffe0\011\uffe0\012\uffe0\026\uffe0\032\uffe0" +
    "\043\uffe0\001\002\000\024\021\060\022\056\027\115\042" +
    "\117\043\043\044\054\045\061\046\062\047\057\001\002" +
    "\000\006\030\uffda\031\uffda\001\002\000\006\030\163\031" +
    "\162\001\002\000\024\030\uffd8\031\uffd8\033\125\034\127" +
    "\035\132\036\130\037\124\040\133\041\131\001\002\000" +
    "\024\021\060\022\056\027\115\042\117\043\043\044\054" +
    "\045\061\046\062\047\057\001\002\000\004\023\164\001" +
    "\002\000\016\003\uffdf\011\uffdf\012\uffdf\026\uffdf\032\uffdf" +
    "\043\uffdf\001\002\000\006\030\uffd9\031\uffd9\001\002\000" +
    "\004\026\uffe7\001\002\000\004\006\ufff9\001\002\000\004" +
    "\002\uffff\001\002\000\004\006\012\001\002\000\004\002" +
    "\000\001\002\000\004\002\ufffe\001\002\000\006\023\175" +
    "\024\021\001\002\000\006\005\ufff8\006\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\016\002\013\003\006\004\005\005\007\007" +
    "\004\014\014\001\001\000\004\006\173\001\001\000\002" +
    "\001\001\000\004\007\172\001\001\000\010\004\170\005" +
    "\007\007\167\001\001\000\006\004\166\005\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\016\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\010\032\011\036\012\030\013\033\014\025\025\026\026" +
    "\044\001\001\000\002\001\001\000\006\022\065\026\066" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\010\063\011\036\012\030\013" +
    "\033\014\025\025\026\026\044\001\001\000\002\001\001" +
    "\000\006\025\047\026\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\026\050\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\027\054\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\030\071\001\001\000\002\001\001\000\004" +
    "\026\074\001\001\000\004\027\073\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\015\111\016\101\017\102\020\110\021\104\026\112" +
    "\001\001\000\016\015\165\016\101\017\102\020\110\021" +
    "\104\026\112\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\026\121\027\115\031\146\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\026\121\027" +
    "\115\031\117\001\001\000\010\026\121\027\115\031\143" +
    "\001\001\000\002\001\001\000\010\026\121\027\115\031" +
    "\142\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\026\121\027\115\031" +
    "\141\001\001\000\010\026\121\027\115\031\140\001\001" +
    "\000\002\001\001\000\010\026\121\027\115\031\137\001" +
    "\001\000\010\026\121\027\115\031\136\001\001\000\010" +
    "\026\121\027\115\031\135\001\001\000\010\026\121\027" +
    "\115\031\134\001\001\000\010\026\121\027\115\031\133" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\022\152\026\066\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\023\157\024\156\026\121\027\115\031\160\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\024\164\026\121\027\115\031\160\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\171\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser5$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser5$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser5$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        String tokenStr = "desconocido";
        int linea = 0;
        int columna = 0;

        if (info instanceof Symbol) {
            Symbol simbolo = (Symbol) info;
            linea = simbolo.left;
            columna = simbolo.right;
            tokenStr = (simbolo.value != null) ? simbolo.value.toString() : "EOF";
        }

        System.out.println("Error sintactico en linea " + linea + ", columna " + columna + ":");
        System.out.println("se encontro '" + tokenStr + "'");
        System.out.println("Descripcion: " + message);
    }

    public void report_fatal_error(String message, Object info) throws Exception {
        report_error(message, info);
        throw new Exception("Error fatal en el analisis sintactico.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser5$actions {
  private final Parser5 parser;

  /** Constructor */
  CUP$Parser5$actions(Parser5 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser5$do_action_part00000000(
    int                        CUP$Parser5$act_num,
    java_cup.runtime.lr_parser CUP$Parser5$parser,
    java.util.Stack            CUP$Parser5$stack,
    int                        CUP$Parser5$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser5$result;

      /* select the action based on the action number */
      switch (CUP$Parser5$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= archivo EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)).value;
		RESULT = start_val;
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser5$parser.done_parsing();
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // archivo ::= paquete importaciones clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // archivo ::= paquete clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // archivo ::= importaciones clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // archivo ::= clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // archivo ::= metodo 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // paquete ::= PAQUETE ubicacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("paquete",1, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // importaciones ::= importacion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("importaciones",2, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // importaciones ::= importacion importaciones 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("importaciones",2, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // importacion ::= IMPORTAR ubicacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("importacion",3, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ubicacion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("ubicacion",4, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ubicacion ::= ubicacion PUNTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("ubicacion",4, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // clase_principal ::= CLASE IDENTIFICADOR LLAVE_A LLAVE_C 
            {
              Object RESULT =null;
		 System.out.println("Clase vacia reconocida."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("clase_principal",5, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // clase_principal ::= CLASE IDENTIFICADOR LLAVE_A cuerpo_clase LLAVE_C 
            {
              Object RESULT =null;
		 System.out.println("Clase con miembros reconocida."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("clase_principal",5, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-4)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // cuerpo_clase ::= miembro cuerpo_clase 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",6, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // cuerpo_clase ::= miembro 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",6, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // miembro ::= atributo 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("miembro",7, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // miembro ::= constante 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("miembro",7, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // miembro ::= metodo 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("miembro",7, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // miembro ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Declaracion invalida recuperada; se continua con el siguiente miembro."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("miembro",7, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // atributo ::= tipo lista_identificadores opt_inicializacion PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Atributo o variable reconocido."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("atributo",8, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // constante ::= FINAL tipo identificador IGUAL valor PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Constante reconocida."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("constante",9, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-5)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // constante ::= FINAL tipo identificador PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error: la constante debe inicializarse."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("constante",9, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // opt_inicializacion ::= IGUAL valor 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("opt_inicializacion",22, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // opt_inicializacion ::= 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("opt_inicializacion",22, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // metodo ::= VOID IDENTIFICADOR PAREN_A PAREN_C LLAVE_A cuerpo_metodo LLAVE_C 
            {
              Object RESULT =null;
		 System.out.println("Metodo reconocido."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("metodo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-6)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // cuerpo_metodo ::= sentencia cuerpo_metodo 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("cuerpo_metodo",11, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // cuerpo_metodo ::= 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("cuerpo_metodo",11, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia ::= lectura 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("sentencia",12, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia ::= escritura 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("sentencia",12, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("sentencia",12, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia ::= IGUAL expresion PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error: identificador esperado en la asignacion."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("sentencia",12, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Sentencia invalida recuperada; se continua con la siguiente sentencia."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("sentencia",12, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lectura ::= LEER PAREN_A lista_identificadores PAREN_C PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: lectura"); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("lectura",13, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-4)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // escritura ::= ESCRIBIR PAREN_A lista_elementos PAREN_C PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: escritura"); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("escritura",14, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-4)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // asignacion ::= identificador IGUAL expresion PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: asignacion"); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("asignacion",15, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // asignacion ::= identificador IGUAL error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error: expresion invalida o incompleta en la asignacion."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("asignacion",15, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // lista_identificadores ::= identificador 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("lista_identificadores",16, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_identificadores ::= lista_identificadores COMA identificador 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("lista_identificadores",16, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_elementos ::= elemento 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("lista_elementos",17, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // lista_elementos ::= lista_elementos COMA elemento 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("lista_elementos",17, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // elemento ::= expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("elemento",18, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion ::= expresion O expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion ::= expresion Y expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresion ::= expresion MAS expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion ::= expresion MENOS expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= expresion POR expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= expresion DIV expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= expresion MOD expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= NO expresion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= PAREN_A expresion PAREN_C 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= identificador 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= valor 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("expresion",23, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // tipo ::= INT 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",19, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // tipo ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",19, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // tipo ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",19, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // tipo ::= CHAR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",19, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // tipo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",19, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // tipo ::= STRING 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",19, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // tipo ::= identificador 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",19, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // identificador ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("identificador",20, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // valor ::= NUMERO 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // valor ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // valor ::= CADENA 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // valor ::= CARACTER 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // valor ::= VERDADERO 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // valor ::= FALSO 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser5$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser5$do_action(
    int                        CUP$Parser5$act_num,
    java_cup.runtime.lr_parser CUP$Parser5$parser,
    java.util.Stack            CUP$Parser5$stack,
    int                        CUP$Parser5$top)
    throws java.lang.Exception
    {
              return CUP$Parser5$do_action_part00000000(
                               CUP$Parser5$act_num,
                               CUP$Parser5$parser,
                               CUP$Parser5$stack,
                               CUP$Parser5$top);
    }
}

}
